config/routes.rb
Tg::Application.routes.draw do

  root :to => 'dashboard#index'
  resources :dashboard
  resources :dishes
  resources :events

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  attr_accessible :cook_time, :event_id, :name, :start_time
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :name, :eat_time
  has_many :dishes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @events = Event.all
  end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

  def new
    @event = Event.find(params[:event])
    @dish = @event.dishes.new
  end

  def create
    @event = Event.find(params[:event])
    @dish = @event.dishes.new(params[:dish])
    @dish.start_time = @event.eat_time - @dish.cook_time.hours
    if @dish.save
      redirect_to event_path(@dish.event.id), notice: 'Dish was successfully created.'
    else
      render action: "new"
    end
  end

  def edit
    @dish = Dish.find(params[:id])
    @event = @dish.event
  end

  def update
    @dish = Dish.find(params[:id])
    @dish.start_time = @dish.event.eat_time - @dish.cook_time.hours
    if @dish.update_attributes(params[:dish])
      redirect_to event_path(@dish.event), notice: 'Dish was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy
    flash[:message] = "Dish successfully removed"
    redirect_to root_path
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(params[:event])
    flash[:notice] = "Successfully created Event"
    redirect_to root_path
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update_attributes(params[:event])
    redirect_to root_path
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dashboard/index.html.haml
%h2
  Select an event below

.row-fluid
  .btn.pull-right= link_to "New Event", new_event_path

%h3
  - if @events
    %table.table.table-bordered.table-striped
      %tr
        %th Event Name
        %th Event Date
        %th Actions
      - @events.each do |event|
        %tr
          %td= link_to event.name, event_path(event)
          %td= event.created_at.strftime("%m/%d/%Y")
          %td
            = link_to "Edit", edit_event_path(event)
            |
            = link_to 'Delete', event, confirm: 'Are you sure?', method: :delete

app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Cook Time (hrs)" %><br />
    <%= f.number_field :cook_time %>
  </div>
  <div class="field">
    <%= hidden_field_tag :event, @event.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= render 'form' %>

app/views/dishes/index.html.erb
<h1>Listing dishes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Start time</th>
    <th>Cook time</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dishes.each do |dish| %>
  <tr>
    <td><%= dish.name %></td>
    <td><%= dish.start_time %></td>
    <td><%= dish.cook_time %></td>
    <td><%= dish.event_id %></td>
    <td><%= link_to 'Show', dish %></td>
    <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
    <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dish.name %>
</p>

<p>
  <b>Start time:</b>
  <%= @dish.start_time %>
</p>

<p>
  <b>Cook time:</b>
  <%= @dish.cook_time %>
</p>

<p>
  <b>Event:</b>
  <%= @dish.event_id %>
</p>


<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

app/views/events/_form.html.haml
= form_for @event do |f|
  .clearfix
    = f.label :name
    = f.text_field :name
  .clearfix
    = f.label :eat_time
    = f.datetime_select :eat_time
  = f.submit

app/views/events/edit.html.haml
%h2 Edit Event

= render 'form'

app/views/events/new.html.haml
%h2 New Event

= form_for @event do |f|
  .clearfix
    = f.label :name
    = f.text_field :name
  .clearfix
    = f.label :eat_time
    = f.datetime_select :eat_time
  = f.submit

app/views/events/show.html.haml
- if @event
  %h2= "Event: #{@event.name} - #{@event.created_at.strftime("%m/%d/%Y")}"
  .eat_time
    %h3
      Eat Time:
      = @event.eat_time.strftime("%I:%M %p")
  .row-fluid
    .btn.pull-right= link_to "New Dish", new_dish_path(event: @event.id)
  %table.table.table-bordered.table-striped
    %tr
      %th Dish Name
      %th Dish Prep Time (hrs)
      %th Start Cooking at:
      %th Actions
    - @event.dishes.each do |dish|
      %tr
        %td= dish.name
        %td= dish.cook_time
        %td= dish.start_time.strftime("%I:%M %p")
        %td
          = link_to "Edit", edit_dish_path(dish)
          |
          = link_to 'Delete', dish, confirm: 'Are you sure?', method: :delete

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipe Timer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
  <%= render 'shared/nav' %>

  <% if alert %>
    <p class="alert-message warning alert alert-error"><%= alert %></p>
  <% end %>
  <% if notice %>
    <p class="alert-message info alert alert-success"><%= notice %></p>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/shared/_nav.html.haml
.navbar
  .navbar-inner
    = link_to "Recipe Timer", root_path, :class => "brand"